plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.videoengine'
version = '0.1.0'

def media3Version = "1.11.1"

android {
  namespace "expo.modules.videoengine"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "androidx.media3:media3-common:$media3Version"
  implementation "androidx.media3:media3-exoplayer:$media3Version"
  implementation "androidx.media3:media3-ui:$media3Version"
  implementation "androidx.media3:media3-transformer:$media3Version"
  implementation "androidx.media3:media3-effect:$media3Version"
}
